version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gafargan_bot_db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_API_TOKEN=<TELEGRAM_API_TOKEN>